# Generated by Django 2.1.2 on 2018-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('gen', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
