# Generated by Django 2.1.2 on 2018-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='entry_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=10, unique=True),
        ),
    ]
