# Generated by Django 2.1.2 on 2018-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_auto_20181009_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=10),
        ),
    ]
