# Generated by Django 2.1.2 on 2018-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_auto_20181009_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='entry_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
