# Generated by Django 2.1.2 on 2018-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='register',
            name='entry_no',
        ),
        migrations.AddField(
            model_name='expenses',
            name='mobile',
            field=models.CharField(default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
