# Generated by Django 2.1.2 on 2018-10-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0006_auto_20181010_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='type',
        ),
        migrations.AddField(
            model_name='expenses',
            name='desc',
            field=models.CharField(default=10, max_length=250),
        ),
        migrations.AddField(
            model_name='expenses',
            name='dt',
            field=models.CharField(default=10, max_length=10),
        ),
        migrations.AddField(
            model_name='expenses',
            name='type_exp',
            field=models.CharField(default=5, max_length=30),
        ),
    ]
