# Generated by Django 2.1.2 on 2018-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0008_auto_20181013_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(default=5),
        ),
    ]
