# Generated by Django 2.1.2 on 2018-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0009_auto_20181013_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='dt',
            field=models.DateField(),
        ),
    ]
