# Generated by Django 2.1.2 on 2018-10-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0010_auto_20181013_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='desc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type_exp',
            field=models.CharField(max_length=30),
        ),
    ]
